### PR TITLE
Add instructions for installing from official Debian/Ubuntu repositories

### PR DESCRIPTION
**Pull request by d-torrance**

### CODE REVIEW

**Comment by d-torrance** [comment]
I'd recommend removing the PPA blurb from the Debian page that was added in f9914f3fdc648ee91e85866ee3a7e444f82f34ac.  They really only support Ubuntu.

**Comment by DanGrayson** [comment]
> I'd recommend removing the PPA blurb from the Debian page that was added in [f9914f3](https://github.com/Macaulay2/Macaulay2-web-site/commit/f9914f3fdc648ee91e85866ee3a7e444f82f34ac). They really only support Ubuntu.

Maybe I can fix it so it appears only on the Ubuntu page.  (The Ubuntu and Debian pages share a common input file.)

**Comment by DanGrayson** [comment]
Thanks, it was a mistake for me to have Downloads/GNU-Linux/Debian/FOOTER.html in the repository, since it's manufactured from Ubuntu/FOOTER0.html, so I've added your text to it and put the correct comments in so it's directed just to the Debian page.

Take a look.

Closing.

**Comment by d-torrance** [comment]
Looks good!

**Pull request closed without merging**
